# Generated by Django 3.1.2 on 2020-10-18 17:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ahang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ahang', models.FileField(upload_to='Musics/')),
                ('publishDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
