# Generated by Django 3.1.2 on 2020-10-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahang',
            old_name='ahang',
            new_name='ahang_file',
        ),
        migrations.AddField(
            model_name='ahang',
            name='ahang_esm',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
