# Generated by Django 3.1.2 on 2020-10-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0002_auto_20201018_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahang',
            options={'verbose_name': 'Music', 'verbose_name_plural': "Music's"},
        ),
    ]
