# Generated by Django 3.1.2 on 2020-11-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0003_auto_20201106_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentdb',
            old_name='ahnag',
            new_name='ahang',
        ),
    ]
