# Generated by Django 3.1.2 on 2020-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0004_commentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdb',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
