# Generated by Django 3.1.2 on 2020-10-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0005_auto_20201020_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdb',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='commentdb',
            name='user_name',
            field=models.CharField(default='nUmberX', max_length=200),
        ),
    ]
