# Generated by Django 3.1.2 on 2020-10-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0006_auto_20201023_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahang',
            name='isAgreed',
            field=models.BooleanField(default=False),
        ),
    ]
