# Generated by Django 3.1.2 on 2020-10-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0008_auto_20201024_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahang',
            name='ahang_esm',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
