# Generated by Django 3.1.2 on 2020-11-05 11:42

import ahang.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0009_auto_20201024_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentdb',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': "Contact's"},
        ),
        migrations.AddField(
            model_name='ahang',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ahang.commentdb'),
        ),
        migrations.AlterField(
            model_name='ahang',
            name='ahang_file',
            field=models.FileField(upload_to='Musics/', validators=[ahang.validators.validate_file]),
        ),
    ]
