# Generated by Django 3.1.2 on 2020-11-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0011_auto_20201105_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahang',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ahang.commentdb'),
        ),
    ]
