# Generated by Django 3.1.2 on 2020-11-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0012_auto_20201105_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahang',
            name='comment',
        ),
        migrations.AlterField(
            model_name='commentdb',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahang.ahang'),
        ),
    ]
