# Generated by Django 3.1.2 on 2020-11-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahang', '0013_auto_20201105_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdb',
            name='ahang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ahang.ahang'),
        ),
        migrations.AlterField(
            model_name='commentdb',
            name='comment',
            field=models.TextField(),
        ),
    ]
